Repository be19-1st-FirstClass/be19-1st-FirstClass-TastyActing, pull requests merged in 2025-08, with the labels that each got.

#34 배우 리뷰 CRUD
  actor/배우 리뷰 삭제.sql
  actor/배우 리뷰 수정.sql
  actor/배우 리뷰 작성.sql
  actor/배우 리뷰 정렬.sql
Labels: Enhancement

#33 관리자_사용자 관리 기능
  admin/사용자 활동 정지 및 영구 정지.sql
  admin/활동 정지 사용자 해제.sql
  admin/회원 정보 조회.sql
Labels: Enhancement

#38 close #37 - 리뷰 및 댓글에 신고 작성 및 신고 횟수 업데이트 트리거 추가
  movie/리뷰 댓글 신고 작성.sql
  movie/리뷰 댓글 신고 횟수 수정.sql
Labels: Enhancement

#42 close #40, #41 - 좋아요 기능 및 신고 횟수 증가 Trigger 구현
  actor/리뷰 좋아요 수정 트리거.sql
  actor/사용자 좋아요 반영 트리거.sql
  actor/좋아요 기능.sql
  actor/회원 신고횟수 증가 트리거.sql
Labels: Enhancement

#53 조회 기능 및 리뷰 테이블 Soft Delete 기능
  ADMIN/감독 정보 조회.sql
  ADMIN/배우 정보 조회.sql
  ADMIN/신고리뷰_댓글_삭제.sql
  ADMIN/영화 정보 조회.sql
  ADMIN/장르 조회.sql
  DDL/create_tables.sql
  sample_data/sample_data.sql
Labels: Enhancement, update

#49 readme 파일 1차 수정입니다
  README.md
  image/banner.png
  image/byun.jpeg
  image/jeong.jpg
  image/lee.jpeg
  image/nam.jpg
  image/paik.jpeg
Labels: Documentation

#57 Update readme
  README.md
  image/banner.png
Labels: Documentation

#59 closed #58 상영예정작 평점 조회 & 일정 평점 이상만 조회
  actor/상영예정작 예상평점 조회.sql
  actor/일정 평점 이상 상영예정작 조회.sql
Labels: Enhancement

#61 close #60 : admin폴더 이슈 해결
  admin/감독 정보 조회.sql
  admin/감독정보등록.sql
  admin/감독정보삭제.sql
  admin/감독정보수정.sql
  admin/배우 정보 조회.sql
  admin/배우정보등록.sql
  admin/배우정보삭제.sql
  admin/배우정보수정.sql
  admin/블랙리스트 사용자 조회.sql
  admin/사용자등급부여.sql
  admin/영화 정보 조회.sql
  admin/영화 출연 배우 수정.sql
  admin/영화정보등록.sql
  admin/영화정보삭제.sql
  admin/영화정보수정.sql
  admin/장르 조회.sql
  admin/장르등록.sql
  admin/장르삭제.sql
  admin/장르수정.sql
  admin/활동 정지 사용자 조회.sql
Labels: Bug

#62 Update readme
  README.md
  image/UML.png
  image/scenario.png
  image/table1.png
  image/table2.png
  image/table3.png
  image/wbs.png
  image/논리erd.png
  image/물리erd.png
  image/요구사항1.png
  image/요구사항2.png
Labels: Documentation

#63 Update readme
  README.md
  image/리눅스ddl.png
  image/리눅스insert.png
  image/리눅스slave1.png
  image/리눅스slave2.png
Labels: Documentation

#65 리드미 오류 수정
  README.md
Labels: Documentation
